import React, { useEffect, useRef, useState } from 'react';
import {Box, Upload, ArrowUpRight, RotateCcw, Footprints, Layers3, Scan, Ruler, TreePine, PersonStanding, Camera, Download, X, Plus, MoveUp, MoveDown, MoveLeft, MoveRight, Check, Info, PencilRuler, Undo2, Building2, Map, HelpCircle, MousePointer2, Shuffle, Sun} from 'lucide-react';
import {CityScene} from './CityScene.js';
import {SAMPLE_BUILDINGS, WATER, PARKS, ROADS, VIEWPOINTS} from './sample.js';
import {footprintIssue} from './geometry.js';
import './styles.css';

const PUBLIC_BASE = import.meta.env.BASE_URL;

const DEFAULT_WIDTH=480, DEFAULT_DEPTH=330;
const copySample=()=>SAMPLE_BUILDINGS.map(b=>({...b,points:b.points.map(p=>[...p]),floorHeight:b.floorHeight||3,floors:Number.isFinite(b.floors)?b.floors:Math.max(1,Math.round(b.height/(b.floorHeight||3))),floorBasis:b.floorBasis||(Number.isFinite(b.floors)?'drawing':'shadow')}));
function download(data, filename, type){const url=URL.createObjectURL(new Blob([data],{type}));const a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function NumberControl({label,value,onChange,min,max,unit}){const [draft,setDraft]=useState(String(value));useEffect(()=>setDraft(String(value)),[value]);function commit(){const n=Number(draft);if(draft.trim()===''||!Number.isFinite(n)){setDraft(String(value));return;}const next=Math.max(min,Math.min(max,n));setDraft(String(next));onChange(next);}return <label className="number-control"><span>{label}</span><div><input type="number" min={min} max={max} value={draft} onChange={e=>setDraft(e.target.value)} onBlur={commit} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur();}}/><span>{unit}</span></div></label>}
function Toggle({icon:Icon,label,value,onChange}){return <button type="button" className="toggle-row" role="switch" aria-checked={value} onClick={()=>onChange(!value)}><span><Icon size={17}/>{label}</span><i className={value?'switch on':'switch'}><b/></i></button>}
export default function App(){
 const container=useRef(null), engine=useRef(null), fileInput=useRef(null), svgRef=useRef(null), imageUrl=useRef(null), toastTimer=useRef(null);
 const [buildings,setBuildings]=useState(copySample),[sample,setSample]=useState(true),[source,setSource]=useState(`${PUBLIC_BASE}reference.jpg`),[fileName,setFileName]=useState('滨水街区 · 手绘总平面'),[imageRatio,setImageRatio]=useState(DEFAULT_DEPTH/DEFAULT_WIDTH);
 const [siteWidth,setSiteWidth]=useState(DEFAULT_WIDTH),[siteDepth,setSiteDepth]=useState(DEFAULT_DEPTH),[heightFactor,setHeightFactor]=useState(1),[roadWidth,setRoadWidth]=useState(18),[trees,setTrees]=useState(true),[people,setPeople]=useState(true),[whiteMode,setWhiteMode]=useState(false);
 const [renderStyle,setRenderStyle]=useState('render'),[showContext,setShowContext]=useState(true),[contextSeed,setContextSeed]=useState(1),[showFloorLabels,setShowFloorLabels]=useState(true);
 const [selected,setSelected]=useState(null),[view,setView]=useState('orbit'),[mode,setMode]=useState('scene'),[walkPoint,setWalkPoint]=useState(0),[measuring,setMeasuring]=useState(false),[measurement,setMeasurement]=useState(null);
 const [showFootprints,setShowFootprints]=useState(true);
 const [drawing,setDrawing]=useState(false),[points,setPoints]=useState([]),[newFloors,setNewFloors]=useState(6),[help,setHelp]=useState(false),[toast,setToast]=useState(''),[error,setError]=useState(''),[ready,setReady]=useState(false),[exporting,setExporting]=useState(false),[mobilePanel,setMobilePanel]=useState(false);
 const selectedBuilding=buildings.find(b=>b.id===selected);
 const notify=message=>{setToast(message);clearTimeout(toastTimer.current);toastTimer.current=setTimeout(()=>setToast(''),4000);};
 useEffect(()=>{try{engine.current=new CityScene(container.current,{onSelect:setSelected,onReady:()=>{setReady(true);setError('');},onError:e=>setError(String(e?.message||e)),onMeasure:m=>setMeasurement(m.distance)});}catch(e){setError('当前浏览器无法创建三维画面。请使用支持 WebGL 的浏览器，并启用硬件加速。');}return()=>{engine.current?.dispose();clearTimeout(toastTimer.current);if(imageUrl.current)URL.revokeObjectURL(imageUrl.current);};},[]);
 useEffect(()=>{engine.current?.setModel({buildings,water:sample?WATER:[],parks:sample?PARKS:[],roads:sample?ROADS:[],siteWidth,siteDepth,heightFactor,roadWidth,showTrees:trees,showPeople:people,showFloorLabels,whiteMode,renderStyle,showContext,contextSeed});},[buildings,sample,siteWidth,siteDepth,heightFactor,roadWidth,trees,people,showFloorLabels,whiteMode,renderStyle,showContext,contextSeed]);
 useEffect(()=>{engine.current?.setSelected(selected);},[selected,buildings,heightFactor,whiteMode]);
 useEffect(()=>{const escape=e=>{if(e.key==='Escape'){setHelp(false);setDrawing(false);setPoints([]);setMeasuring(false);engine.current?.setMeasureEnabled(false);}};window.addEventListener('keydown',escape);return()=>window.removeEventListener('keydown',escape)},[]);
 useEffect(()=>{if(!help)return;const previous=document.activeElement;const modal=document.querySelector('.help-modal');const trap=e=>{if(e.key!=='Tab'||!modal)return;const focusable=Array.from(modal.querySelectorAll('button,[href],input,[tabindex="0"]'));const first=focusable[0],last=focusable.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}};document.addEventListener('keydown',trap);return()=>{document.removeEventListener('keydown',trap);previous?.focus?.();}},[help]);
 function changeView(next,idx=walkPoint){setMode('scene');setView(next);setMeasuring(false);engine.current?.setMeasureEnabled(false);engine.current?.setView(next,sample?VIEWPOINTS[idx]:undefined);if(next==='walk')setMobilePanel(false);}
 function restore(){setBuildings(copySample());setSample(true);setSource(`${PUBLIC_BASE}reference.jpg`);setImageRatio(DEFAULT_DEPTH/DEFAULT_WIDTH);setFileName('滨水街区 · 手绘总平面');setSiteWidth(DEFAULT_WIDTH);setSiteDepth(DEFAULT_DEPTH);setHeightFactor(1);setRoadWidth(18);setSelected(null);setPoints([]);setDrawing(false);setView('orbit');setMode('scene');setMeasurement(null);setMeasuring(false);engine.current?.setMeasureEnabled(false);requestAnimationFrame(()=>engine.current?.resetView());notify('已载入原图示例，尺寸仍为教学假设。');}
 async function upload(e){const file=e.target.files?.[0];e.target.value='';if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)){notify('请选择 JPG、PNG 或 WebP 图片。');return;}if(file.size>15*1024*1024){notify('图片需小于 15 MB。');return;}const url=URL.createObjectURL(file);const img=new Image();img.onload=()=>{if(imageUrl.current)URL.revokeObjectURL(imageUrl.current);imageUrl.current=url;setSource(url);setSample(false);setBuildings([]);setSelected(null);setImageRatio(img.naturalHeight/img.naturalWidth);setSiteWidth(480);setSiteDepth(Math.round(480*img.naturalHeight/img.naturalWidth));setFileName(file.name);setPoints([]);setDrawing(false);setMode('plan');setMobilePanel(false);setHeightFactor(1);setMeasuring(false);setMeasurement(null);engine.current?.setMeasureEnabled(false);notify('图片已载入。先校准图幅尺寸，再沿建筑轮廓点选描摹。');};img.onerror=()=>{URL.revokeObjectURL(url);notify('无法读取这张图片，请换一张图片。');};img.src=url;}
 function addPoint(e){if(!drawing)return;const svg=svgRef.current;const point=svg.createSVGPoint();point.x=e.clientX;point.y=e.clientY;const local=point.matrixTransform(svg.getScreenCTM().inverse());const x=local.x/1000,z=local.y/(1000*imageRatio);if(x<0||x>1||z<0||z>1)return;setPoints(prev=>[...prev,[x,z]]);}
 function finishFootprint(){const issue=footprintIssue(points);if(issue){notify(issue);return;}const id=`custom-${Date.now()}`;setBuildings(prev=>[...prev,{id,name:`描摹建筑 ${prev.filter(b=>b.id.startsWith('custom')).length+1}`,points:points.map(p=>[...p]),floors:newFloors,floorHeight:3,height:newFloors*3,floorBasis:'manual',kind:newFloors>=12?'tower':newFloors>=6?'slab':'low'}]);setSelected(id);setPoints([]);setDrawing(false);notify(`已按 ${newFloors} 层生成建筑，可直接在同一场景切换鸟瞰与人视。`);}
 async function exportModel(){if(!engine.current||!buildings.length){notify('请先描摹至少一栋建筑。');return;}setExporting(true);try{const data=await engine.current.exportGLB();download(data,'3D城市-教学体块.glb','model/gltf-binary');notify('已导出 GLB 模型，单位为米，尺寸采用当前设置。');}catch(e){notify('模型导出失败，请重试。');}finally{setExporting(false);}}
 function capture(){if(mode==='plan'){notify('请先切换到三维场景再保存视图。');return;}try{const url=engine.current.capture();const a=document.createElement('a');a.href=url;a.download='3D城市-尺度视图.png';a.click();notify('当前三维视图已保存。');}catch(e){notify('视图保存失败，请重试。');}}
 const height=selectedBuilding?selectedBuilding.height*heightFactor:18*heightFactor;
 const footprintPath=b=>[b.points,...(b.holes||[])].map(ring=>'M'+ring.map(p=>`${p[0]*1000},${p[1]*1000*imageRatio}`).join('L')+'Z').join(' ');
 const floorLabelPoint=b=>({x:Math.max(...b.points.map(p=>p[0]))*1000-18,y:Math.max(...b.points.map(p=>p[1]))*1000*imageRatio-7});
 return <div className="app-shell">
  <header className="app-header"><a className="brand" href="#" onClick={e=>e.preventDefault()}><span className="brand-mark"><img src={`${PUBLIC_BASE}app-icon.png`} alt=""/></span><strong>3D城市</strong><span className="brand-divider"/><span className="brand-tag">空间尺度实验室</span></a><div className="header-right"><span className="prototype-label">交互原型 v0.2</span><button className="icon-button" onClick={()=>setHelp(true)} aria-label="使用说明"><HelpCircle size={20}/></button><button className="button primary export-top" onClick={exportModel} disabled={exporting}><Download size={16}/>{exporting?'正在导出…':'导出模型'}</button></div></header>
  <div className="workspace-bar"><div className="project-title"><span className="project-icon"><Map size={19}/></span><span>{fileName}</span><span className="draft-tag">{sample?'参考图推演':'自主描摹'}</span></div><div className="workspace-tabs" aria-label="工作区"><button className={mode==='scene'?'active':''} onClick={()=>{setMode('scene');setDrawing(false);setPoints([]);changeView('orbit');}}><Box size={16}/>效果场景</button><button className={mode==='plan'?'active':''} onClick={()=>{setMode('plan');setMeasuring(false);engine.current?.setMeasureEnabled(false);}}><PencilRuler size={16}/>图纸校对</button></div><button className="mobile-settings button" onClick={()=>setMobilePanel(!mobilePanel)}><Layers3 size={17}/>参数</button></div>
  <div className="workspace">
   <aside className={`sidebar ${mobilePanel?'mobile-open':''}`} aria-label="模型参数"><div className="mobile-panel-heading"><strong>模型参数</strong><button className="icon-button" aria-label="关闭参数" onClick={()=>setMobilePanel(false)}><X size={20}/></button></div>
    <section className="source-section"><div className="section-heading"><h2>原始图纸</h2><span>01</span></div><button className="source-preview" aria-label="查看原始图纸并描摹" onClick={()=>{setMode('plan');setMobilePanel(false);}}>{sample?<img src={source} className="reference-crop" alt="用户提供的滨水街区手绘总平面图"/>:<img src={source} className="uploaded-preview" alt="上传的待描摹平面图"/>}<span><Scan size={14}/>查看平面图<ArrowUpRight size={14}/></span></button><button className="upload-button" onClick={()=>fileInput.current.click()}><Upload size={15}/>导入另一张图纸</button><input ref={fileInput} type="file" accept="image/jpeg,image/png,image/webp" hidden onChange={upload}/><p className="source-note">JPG / PNG / WebP · 仅在本机处理<br/>新图需手动描摹，替换当前练习</p></section>
    <section className="render-section"><div className="section-heading"><h2>画面表现</h2><Sun size={17}/></div><div className="render-style-tabs"><button className={renderStyle==='render'?'active':''} onClick={()=>setRenderStyle('render')}>材质与光影</button><button className={renderStyle==='model'?'active':''} onClick={()=>setRenderStyle('model')}>教学体块</button></div><Toggle icon={Building2} label="显示周边环境" value={showContext} onChange={setShowContext}/><button className="context-shuffle" disabled={!showContext} onClick={()=>{setContextSeed(v=>v+1);notify('已更换随机周边，原图地块内的建筑保持当前设置。');}}><Shuffle size={14}/>换一组周边<span>0{contextSeed}</span></button><p className="field-note">周边、立面与景观是示意设计。<br/>原图没有给出这些信息。</p></section>
    <section><div className="section-heading"><h2>尺度校准</h2><span>02</span></div><div className="assumption-note"><Info size={15}/><span>当前尺寸为假设值，请按图纸校准。</span></div><div className="dimension-inputs"><NumberControl label="图幅宽度" value={siteWidth} onChange={setSiteWidth} min={20} max={3000} unit="m"/><NumberControl label="图幅进深" value={siteDepth} onChange={setSiteDepth} min={20} max={5000} unit="m"/></div><div className="slider-heading"><label htmlFor="height-factor">整体建筑高度</label><strong>{heightFactor.toFixed(2)}<small> ×</small></strong></div><input id="height-factor" aria-label="整体建筑高度" type="range" min="0.4" max="2.5" step="0.05" value={heightFactor} onChange={e=>setHeightFactor(Number(e.target.value))}/><div className="range-labels"><span>更低 · 0.4×</span><span>更高 · 2.5×</span></div>{sample&&<><div className="slider-heading road-heading"><label htmlFor="road-width">路面宽度</label><strong>{roadWidth}<small> m</small></strong></div><input id="road-width" type="range" min="8" max="28" step="1" value={roadWidth} onChange={e=>setRoadWidth(Number(e.target.value))}/><p className="field-note">改变铺装宽度，建筑位置保持不变。</p></>}</section>
    <section className="selection-section"><div className="section-heading"><h2>{selectedBuilding?'所选建筑':'核对建筑层数'}</h2><Building2 size={16}/></div>{selectedBuilding?<><div className="selected-name"><i/>{selectedBuilding.name}<span className={`basis-tag ${selectedBuilding.floorBasis||'manual'}`}>{selectedBuilding.floorBasis==='drawing'?'图纸标注':selectedBuilding.floorBasis==='shadow'?'阴影推测':'人工设定'}</span></div><div className="floor-inputs"><NumberControl label="建筑层数" value={selectedBuilding.floors} onChange={v=>setBuildings(prev=>prev.map(b=>b.id===selected?{...b,floors:Math.round(v),height:Math.round(v)*(b.floorHeight||3),floorBasis:'manual'}:b))} min={1} max={80} unit="层"/><NumberControl label="标准层高" value={selectedBuilding.floorHeight||3} onChange={v=>setBuildings(prev=>prev.map(b=>b.id===selected?{...b,floorHeight:v,height:b.floors*v,floorBasis:'manual'}:b))} min={2.4} max={6} unit="m"/></div><p className="field-note"><b>{selectedBuilding.floors} 层 × {(selectedBuilding.floorHeight||3).toFixed(1)} m</b>，当前显示总高 <b>{height.toFixed(1)} m</b></p>{selectedBuilding.heightSource&&<p className="height-source">识别说明：{selectedBuilding.heightSource}</p>}{selected.startsWith('custom')&&<button className="text-button danger" onClick={()=>{setBuildings(prev=>prev.filter(b=>b.id!==selected));setSelected(null);}}>移除此描摹建筑</button>}</>:<p className="selection-hint"><MousePointer2 size={18}/>点击场景或图纸中的建筑，<br/>核对右下角层数并修改。</p>}</section>
    <section className="display-section"><div className="section-heading"><h2>尺度参照</h2><span>03</span></div><Toggle icon={Layers3} label="显示层数标注" value={showFloorLabels} onChange={setShowFloorLabels}/><Toggle icon={TreePine} label="树木与绿地" value={trees} onChange={setTrees}/><Toggle icon={PersonStanding} label="行人与车辆" value={people} onChange={setPeople}/><Toggle icon={Layers3} label="纯白体块" value={whiteMode} onChange={setWhiteMode}/></section>
    <button className="restore-button" onClick={restore}><RotateCcw size={14}/>恢复手绘图示例</button><div className="sidebar-bottom">为理解空间而建<span>EST. 2026</span></div>
   </aside>
   <main className={`stage ${view==='walk'?'is-walk':''}`} aria-label="城市空间工作区">
    <div className={`scene-container ${mode!=='scene'?'scene-hidden':''}`} ref={container}/>
    {error&&mode==='scene'&&<div className="canvas-error"><Info size={30}/><h2>三维画面暂时无法显示</h2><p>{error}</p><button className="button" onClick={()=>setMode('plan')}>继续使用平面描摹</button></div>}
    {mode==='scene'&&<><div className="viewport-toolbar"><div className="view-controls"><button className={view==='orbit'?'active':''} onClick={()=>changeView('orbit')}><Camera size={16}/>鸟瞰效果</button><button className={view==='walk'?'active':''} onClick={()=>changeView('walk')}><Footprints size={16}/>人视漫游</button><button className={view==='top'?'active':''} onClick={()=>changeView('top')}><Scan size={16}/>正投顶视</button></div><button title="地面两点测距" className={`measure-button ${measuring?'active':''}`} onClick={()=>{const v=!measuring;setMeasuring(v);setMeasurement(null);engine.current?.setMeasureEnabled(v);notify(v?'在地面上依次点击两点，测量水平距离。':'已退出测距。');}}><Ruler size={17}/><span>测距</span></button></div><div className="scene-caption"><span>{view==='walk'?'行走在同一个效果场景里':view==='top'?'核对图纸、轮廓与层数':'可游览的实时鸟瞰效果'}</span><small>{sample?'同一份建筑、立面、绿化和层数数据实时切换视角':'根据手动描摹的轮廓与层数生成'}</small></div><div className="north"><span>N</span><div>↑</div></div><div className="right-tools"><button aria-label="恢复鸟瞰视角" title="恢复鸟瞰视角" onClick={()=>{changeView('orbit');engine.current?.resetView();}}><RotateCcw size={18}/></button><button aria-label="保存当前视图" title="保存当前视图" onClick={capture}><Camera size={18}/></button></div>
    {measurement!==null&&<div className="measurement-result"><Ruler size={17}/><strong>{measurement.toFixed(1)} m</strong><span>地面水平距离 · 基于当前比例</span><button aria-label="关闭测距" onClick={()=>{setMeasurement(null);setMeasuring(false);engine.current?.setMeasureEnabled(false);}}><X size={14}/></button></div>}
    {view==='walk'?<><div className="eye-level"><PersonStanding size={22}/><div><strong>1.70 <small>m</small></strong><span>你的视线高度</span></div></div><div className="walk-pad" aria-label="步行方向"><button aria-label="向前走" onClick={()=>engine.current?.moveWalk('forward')}><MoveUp size={21}/></button><div><button aria-label="向左走" onClick={()=>engine.current?.moveWalk('left')}><MoveLeft size={21}/></button><button aria-label="向后走" onClick={()=>engine.current?.moveWalk('backward')}><MoveDown size={21}/></button><button aria-label="向右走" onClick={()=>engine.current?.moveWalk('right')}><MoveRight size={21}/></button></div></div></>:<div className="model-legend"><span><i className="legend-low"/>低层体块</span><span><i className="legend-tower"/>高层体块</span><span><i className="legend-water"/>水体</span></div>}
    <div className="experience-panel"><div className="experience-title"><div className="walking-icon"><Footprints size={21}/></div><div><h2>把自己放进图纸里</h2><p>从 1.70 米的视线，重新认识一条街。</p></div><span className="viewpoint-count">{sample?'3 个观察点':'自由探索'}</span></div><div className="viewpoint-buttons">{sample?VIEWPOINTS.map((p,i)=><button key={p.id} className={view==='walk'&&walkPoint===i?'active':''} onClick={()=>{setWalkPoint(i);changeView('walk',i);}}><span>0{i+1}</span>{p.name}<ArrowUpRight size={15}/></button>):<button onClick={()=>changeView('walk')}><Footprints size={16}/>进入人视漫游<ArrowUpRight size={15}/></button>}</div></div><div className="canvas-hint">{view==='walk'?'拖拽环顾 · W A S D 或方向按钮行走 · 已启用简化碰撞':measuring?'在地面依次点选两个位置':'拖拽旋转 · 滚轮缩放 · 右键平移'}</div></>}
    {mode==='plan'&&<div className="plan-workspace"><div className="plan-heading"><div><h1>沿轮廓校对建筑，按层数决定高度。</h1><p>{drawing?'依次点选建筑角点，填入图纸右下角的层数，再生成建筑。':'绿色范围是建筑占地；无“≈”的是图纸标注，有“≈”的是保守估计。点击任意建筑即可校正。'}</p></div><div className="plan-actions"><button className="button" onClick={()=>setShowFootprints(v=>!v)}>{showFootprints?'只看原图':'显示推演'}</button><button className="button primary" onClick={()=>{setDrawing(!drawing);setPoints([]);}} >{drawing?<X size={16}/>:<Plus size={16}/>} {drawing?'取消描摹':'描摹建筑'}</button></div></div><div className={`plan-canvas ${drawing?'drawing':''}`}><svg ref={svgRef} viewBox={`0 0 1000 ${1000*imageRatio}`} onClick={addPoint} aria-label="平面图描摹画布"><defs><clipPath id="plan-clip"><rect width="1000" height={1000*imageRatio}/></clipPath></defs><g clipPath="url(#plan-clip)"><image href={source} x="0" y={sample?-733:0} width="1000" height={sample?2163.28:1000*imageRatio} preserveAspectRatio="none"/>{showFootprints&&buildings.map(b=><path key={b.id} d={footprintPath(b)} fillRule="evenodd" className={`building-footprint ${selected===b.id?'selected':''}`} onClick={e=>{if(!drawing){e.stopPropagation();setSelected(b.id);}}}/>)}{showFootprints&&showFloorLabels&&buildings.map(b=>{const p=floorLabelPoint(b);return <g key={`floor-${b.id}`} className={`plan-floor-label ${b.floorBasis==='shadow'?'estimated':''} ${selected===b.id?'selected':''}`} transform={`translate(${p.x} ${p.y})`} onClick={e=>{if(!drawing){e.stopPropagation();setSelected(b.id);}}}><rect x="-24" y="-14" width="48" height="24" rx="5"/><text textAnchor="middle" y="4">{b.floorBasis==='shadow'?'≈':''}{b.floors}F</text></g>})}{points.length>0&&<><polyline points={points.map(p=>`${p[0]*1000},${p[1]*1000*imageRatio}`).join(' ')} className="drawing-line"/>{points.map((p,i)=><circle key={i} cx={p[0]*1000} cy={p[1]*1000*imageRatio} r="5" className="drawing-point"/>)}</>}</g></svg></div>{drawing?<div className="drawing-controls"><span>已选 <b>{points.length}</b> 个角点</span><NumberControl label="图纸层数" value={newFloors} onChange={v=>setNewFloors(Math.round(v))} min={1} max={80} unit="层"/><button className="button" disabled={!points.length} onClick={()=>setPoints(prev=>prev.slice(0,-1))}><Undo2 size={16}/>撤销</button><button className="button primary" disabled={points.length<3} onClick={finishFootprint}><Check size={16}/>生成建筑</button></div>:<div className="plan-notice"><Info size={16}/><span>{sample?'21F、17F、11F 按可辨认标注生成；未标注的滨水建筑约 1–3 层，裙房约 2–3 层，较大板楼约 3–5 层。估计值均可修改。':'描摹时直接输入层数，默认按 3 米标准层高生成；之后仍可逐栋修改。'}</span><button onClick={()=>{setMode('scene');changeView('orbit');}}>进入同一效果场景<ArrowUpRight size={15}/></button></div>}</div>}
   </main>
  </div>
  <footer className="statusbar"><div><span className={`status-indicator ${ready?'ready':''}`}/>{ready?'场景就绪':'正在准备三维场景'}<span className="footer-divider"/>{buildings.length} 个建筑体块<span className="footer-divider"/><span className="area-text">图幅 {(siteWidth*siteDepth/10000).toFixed(2)} ha</span></div><div><Info size={13}/><span>教学推演 · 非实测模型</span><button onClick={exportModel} disabled={exporting} className="mobile-export"><Download size={15}/>导出</button></div></footer>
  {toast&&<div className="toast" role="status"><Info size={17}/>{toast}</div>}
  {help&&<div className="modal-backdrop" onClick={()=>setHelp(false)}><section className="help-modal" role="dialog" aria-modal="true" aria-labelledby="help-title" onClick={e=>e.stopPropagation()}><button autoFocus className="icon-button modal-close" aria-label="关闭使用说明" onClick={()=>setHelp(false)}><X size={22}/></button><span className="modal-eyebrow">3D城市 / 使用说明</span><h1 id="help-title">先看懂尺度，再完善设计。</h1><ol><li><strong>校准一个已知尺寸</strong><p>示例暂按 480 × 330 米图幅建立。输入真实图幅宽度、进深，模型才有可信的水平尺度。</p></li><li><strong>为建筑赋予高度</strong><p>单击建筑可修改基础高度；整体倍率用于比较同一街区的高低变化。全部高度都是可修改的假设。</p></li><li><strong>切到人视角去感受</strong><p>用观察点进入街道，以 1.70 米眼高行走。拖动环顾，WASD 或屏幕按钮移动。树木、行人和车辆提供比例参照。</p></li><li><strong>用自己的图纸建立体块</strong><p>导入图片后，在「平面描摹」按顺序点击每栋建筑角点，再生成体块。此原型尚未接入自动图像识别。</p></li></ol><div className="help-limitation">原图比例与部分层数标记不清晰，本模型结合屋顶、阴影和候选层数进行近似推演。采用3米层高假设，无法恢复被遮挡边界、真实立面和地形。随机周边不是原图的真实环境。步行碰撞为简化模拟。练习仅保留在当前页面，可导出以米为单位的 GLB 模型供支持该格式的三维工具使用。</div><button className="button primary" onClick={()=>setHelp(false)}>开始探索<ArrowUpRight size={16}/></button></section></div>}
 </div>
}
